language: c
branches:
  except:
  - debian
os:
  - linux
compiler:
  - clang
  - gcc
install: 
  - sh .travis/before_install
group: travis_latest
script: ./autogen.sh && dpkg-buildpackage -rfakeroot -uc -us -i -I.git
